# This file defines which platform components are deployed in this cluster.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-prod
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/emirates/platform-devsecops.git
    path: clusters/prod
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
