apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booking
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: booking
  source:
    repoURL: https://github.com/emirates/platform-devsecops.git
    path: apps/booking/overlays/staging
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
